# pyproject.toml
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quanten_benchmarking"   
version = "0.0.1"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools.packages.find]
include = ["model*"]
